### ISSUE TITLE
Feature Request - Free stuck unit

### ISSUE THREAD

**Issue by CargoVroom** [ajkroeg/StrategicOperations#1]
Reminder of the idea we talked about on discord.

Since sometimes units get stuck on deployment, or very rarely on strange terrain features during gameplay.
An ability that moves a unit a very short distance horizontally could be useful. Ideally it would be set up to only be attractive to fix glitches not to use in ordinary play.

"we can give it fairly serious penalties for use. lose all evasion, give it a big cbill cost, only allow it to be used once or twice per mission, etc. could probably limit the range vertically as well... so you can use it to get off a weird ramp on an urban map or whatever, but not teleport to the top of a building."

**Comment by ajkroeg** [comment]
@CargoVroom remind me... is this resolved by the CarefulManeuvers ability, or did you want like...an actual emergency teleport ability? Only a month ago and I've completely forgotten what we talked about -_-
